# Copyright 2021 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: "Deploy to Cloud Run"
    name: "gcr.io/cloud-builders/gcloud:latest"
    args:
      - beta
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --source .
      - --execution-environment=gen2
      - --vpc-connector=${_CONNECTOR}
      - --update-env-vars=FILESTORE_IP_ADDRESS=${_FILESTORE_IP_ADDRESS},FILE_SHARE_NAME=${_FILESHARE}
      - --region=${_DEPLOY_REGION}
      - --no-allow-unauthenticated

substitutions:
  _SERVICE_NAME: filesystem
  _DEPLOY_REGION: us-central1
  _FILESHARE: vol1
  _CONNECTOR: my-run-connector
  _FILESTORE_IP_ADDRESS: 0.0.0.0
