path:
  pullrequest: true
  labelprefix: "api: "
  paths:
    appengine: "appengine"
    asset: "asset"
    auth: "auth"
    automl: "automl"
    batch: "batch"
    bigquery: "bigquery"
    bigquery_storage: "bigquerystorage"
    billing: "cloudbilling"
    cloud_tasks: "tasks"
    cloud-sql: "cloudsql"
    cloudbuild: "cloudbuild"
    composer: "composer"
    compute: "compute"
    contact-center-insights: "contactcenterinsights"
    container: "container"
    container-analysis: "containeranalysis"
    datacatalog: "datacatalog"
    datalabeling: "datalabeling"
    dataproc: "dataproc"
    datastore: "datastore"
    dialogflow: "dialogflow"
    dlp: "dlp"
    dns: "dns"
    documentai: "documentai"
    endpoints: "endpoints"
    error_reporting: "clouderrorreporting"
    eventarc: "eventarc"
    firestore: "firestore"
    functions: "cloudfunctions"
    healthcare: "healhcare"
    iam: "iam"
    iap: "iap"
    iot: "cloudiot"
    jobs: "jobs"
    kms: "cloudkms"
    kubernetes_engine: "container"
    language: "language"
    media_cdn: "edgecache"
    media-translation: "mediatranslation"
    memorystore: "memorystore"
    ml_engine: "ml"
    monitoring: "monitoring"
    notebooks: "notebooks"
    optimization: "cloudoptimization"
    profiler: "cloudprofiler"
    pubsub: "pubsub"
    pubsublite: "pubsublite"
    retail: "retail"
    run: "run"
    scheduler: "cloudscheduler"
    secretmanager: "secretmanager"
    securitycenter: "securitycenter"
    servicedirectory: "servicedirectory"
    spanner: "spanner"
    speech: "speech"
    storage: "storage"
    storagetransfer: "storagetransfer"
    talent: "jobs"
    texttospeech: "texttospeech"
    trace: "cloudtrace"
    translate: "translate"
    vision: "vision"
    webrisk: "webrisk"
    workflows: "workflows"
