rules:

# Option 5: incoming PRs from renovate-bot
- author: "renovate-bot"

# Title for PRs from renovate-bot MUST start with `fix(deps):` or `chore(deps)"`.
  title: "^(fix|chore)\\(deps\\):"

# (Optional) The only changed file paths in an incoming PR MUST end with `requirements.txt`. These are listed in regex. If this property 
# is omitted, auto-approve bot will allow PRs that match the author and title to merge, without
# checking the file paths. 
  changedFiles:
  - "requirements\\.txt$"
