allowedCopyrightHolders:
  - "Google LLC"
  - "Google, Inc"

allowedLicenses:
  - "Apache-2.0"
  - "MIT"
  - "BSD-3"

ignoreFiles:
  - "**/requirements.txt"
  - "**/requirements-test.txt"
  - "**/requirements-composer.txt"
  - "**/__init__.py"
  - "**/constraints.txt"
  - "**/constraints-test.txt"
  - "**/apt.txt"
  - "**/ghcnd-stations.txt"
  - "texttospeech/snippets/resources/example.txt"
  - "texttospeech/snippets/resources/hello.txt"
  - "language/**/resources/*.txt"
  - "language/snippets/classify_text/resources/texts/*.txt"
  - "dlp/snippets/resources/accounts.txt"
  - "dlp/snippets/resources/harmless.txt"
  - "dlp/snippets/resources/test.txt"

ignoreLicenseYear: true

sourceFileExtensions:
  - "ts"
  - "js"
  - "java"
  - "sh"
  - "Dockerfile"
  - "yaml"
  - "py"
  - "html"
  - "txt"
