# coding: utf-8

"""
    $API_ENDPOINT_URL

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExtraInfoRequestBody(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, info=None, notification_type=None):
        """
        ExtraInfoRequestBody - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'info': 'str',
            'notification_type': 'str'
        }

        self.attribute_map = {
            'info': 'info',
            'notification_type': 'notificationType'
        }

        self._info = info
        self._notification_type = notification_type

    @property
    def info(self):
        """
        Gets the info of this ExtraInfoRequestBody.

        :return: The info of this ExtraInfoRequestBody.
        :rtype: str
        """
        return self._info

    @info.setter
    def info(self, info):
        """
        Sets the info of this ExtraInfoRequestBody.

        :param info: The info of this ExtraInfoRequestBody.
        :type: str
        """

        self._info = info

    @property
    def notification_type(self):
        """
        Gets the notification_type of this ExtraInfoRequestBody.

        :return: The notification_type of this ExtraInfoRequestBody.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type):
        """
        Sets the notification_type of this ExtraInfoRequestBody.

        :param notification_type: The notification_type of this ExtraInfoRequestBody.
        :type: str
        """

        self._notification_type = notification_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExtraInfoRequestBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
