# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AIRPORTS = {
    "ABQ": "Albuquerque International Sunport Airport",
    "ACA": "General Juan N Alvarez International Airport",
    "ADW": "Andrews Air Force Base",
    "AFW": "Fort Worth Alliance Airport",
    "AGS": "Augusta Regional At Bush Field",
    "AMA": "Rick Husband Amarillo International Airport",
    "ANC": "Ted Stevens Anchorage International Airport",
    "ATL": "Hartsfield Jackson Atlanta International Airport",
    "AUS": "Austin Bergstrom International Airport",
    "AVL": "Asheville Regional Airport",
    "BAB": "Beale Air Force Base",
    "BAD": "Barksdale Air Force Base",
    "BDL": "Bradley International Airport",
    "BFI": "Boeing Field King County International Airport",
    "BGR": "Bangor International Airport",
    "BHM": "Birmingham-Shuttlesworth International Airport",
    "BIL": "Billings Logan International Airport",
    "BLV": "Scott AFB/Midamerica Airport",
    "BMI": "Central Illinois Regional Airport at Bloomington-Normal",
    "BNA": "Nashville International Airport",
    "BOI": "Boise Air Terminal/Gowen field",
    "BOS": "General Edward Lawrence Logan International Airport",
    "BTR": "Baton Rouge Metropolitan, Ryan Field",
    "BUF": "Buffalo Niagara International Airport",
    "BWI": "Baltimore/Washington International Thurgood Marshall Airport",
    "CAE": "Columbia Metropolitan Airport",
    "CBM": "Columbus Air Force Base",
    "CHA": "Lovell Field",
    "CHS": "Charleston Air Force Base-International Airport",
    "CID": "The Eastern Iowa Airport",
    "CLE": "Cleveland Hopkins International Airport",
    "CLT": "Charlotte Douglas International Airport",
    "CMH": "Port Columbus International Airport",
    "COS": "City of Colorado Springs Municipal Airport",
    "CPR": "Casper-Natrona County International Airport",
    "CRP": "Corpus Christi International Airport",
    "CRW": "Yeager Airport",
    "CUN": "Canc\xfan International Airport",
    "CVG": "Cincinnati Northern Kentucky International Airport",
    "CVS": "Cannon Air Force Base",
    "DAB": "Daytona Beach International Airport",
    "DAL": "Dallas Love Field",
    "DAY": "James M Cox Dayton International Airport",
    "DBQ": "Dubuque Regional Airport",
    "DCA": "Ronald Reagan Washington National Airport",
    "DEN": "Denver International Airport",
    "DFW": "Dallas Fort Worth International Airport",
    "DLF": "Laughlin Air Force Base",
    "DLH": "Duluth International Airport",
    "DOV": "Dover Air Force Base",
    "DSM": "Des Moines International Airport",
    "DTW": "Detroit Metropolitan Wayne County Airport",
    "DYS": "Dyess Air Force Base",
    "EDW": "Edwards Air Force Base",
    "END": "Vance Air Force Base",
    "ERI": "Erie International Tom Ridge Field",
    "EWR": "Newark Liberty International Airport",
    "FAI": "Fairbanks International Airport",
    "FFO": "Wright-Patterson Air Force Base",
    "FLL": "Fort Lauderdale Hollywood International Airport",
    "FSM": "Fort Smith Regional Airport",
    "FTW": "Fort Worth Meacham International Airport",
    "FWA": "Fort Wayne International Airport",
    "GDL": "Don Miguel Hidalgo Y Costilla International Airport",
    "GEG": "Spokane International Airport",
    "GPT": "Gulfport Biloxi International Airport",
    "GRB": "Austin Straubel International Airport",
    "GSB": "Seymour Johnson Air Force Base",
    "GSO": "Piedmont Triad International Airport",
    "GSP": "Greenville Spartanburg International Airport",
    "GUS": "Grissom Air Reserve Base",
    "HIB": "Range Regional Airport",
    "HMN": "Holloman Air Force Base",
    "HMO": "General Ignacio P. Garcia International Airport",
    "HNL": "Honolulu International Airport",
    "HOU": "William P Hobby Airport",
    "HSV": "Huntsville International Carl T Jones Field",
    "HTS": "Tri-State/Milton J. Ferguson Field",
    "IAD": "Washington Dulles International Airport",
    "IAH": "George Bush Intercontinental Houston Airport",
    "ICT": "Wichita Mid Continent Airport",
    "IND": "Indianapolis International Airport",
    "JAN": "Jackson-Medgar Wiley Evers International Airport",
    "JAX": "Jacksonville International Airport",
    "JFK": "John F Kennedy International Airport",
    "JLN": "Joplin Regional Airport",
    "LAS": "McCarran International Airport",
    "LAX": "Los Angeles International Airport",
    "LBB": "Lubbock Preston Smith International Airport",
    "LCK": "Rickenbacker International Airport",
    "LEX": "Blue Grass Airport",
    "LFI": "Langley Air Force Base",
    "LFT": "Lafayette Regional Airport",
    "LGA": "La Guardia Airport",
    "LIT": "Bill & Hillary Clinton National Airport/Adams Field",
    "LTS": "Altus Air Force Base",
    "LUF": "Luke Air Force Base",
    "MBS": "MBS International Airport",
    "MCF": "Mac Dill Air Force Base",
    "MCI": "Kansas City International Airport",
    "MCO": "Orlando International Airport",
    "MDW": "Chicago Midway International Airport",
    "MEM": "Memphis International Airport",
    "MEX": "Licenciado Benito Juarez International Airport",
    "MGE": "Dobbins Air Reserve Base",
    "MGM": "Montgomery Regional (Dannelly Field) Airport",
    "MHT": "Manchester Airport",
    "MIA": "Miami International Airport",
    "MKE": "General Mitchell International Airport",
    "MLI": "Quad City International Airport",
    "MLU": "Monroe Regional Airport",
    "MOB": "Mobile Regional Airport",
    "MSN": "Dane County Regional Truax Field",
    "MSP": "Minneapolis-St Paul International/Wold-Chamberlain Airport",
    "MSY": "Louis Armstrong New Orleans International Airport",
    "MTY": "General Mariano Escobedo International Airport",
    "MUO": "Mountain Home Air Force Base",
    "OAK": "Metropolitan Oakland International Airport",
    "OKC": "Will Rogers World Airport",
    "ONT": "Ontario International Airport",
    "ORD": "Chicago O'Hare International Airport",
    "ORF": "Norfolk International Airport",
    "PAM": "Tyndall Air Force Base",
    "PBI": "Palm Beach International Airport",
    "PDX": "Portland International Airport",
    "PHF": "Newport News Williamsburg International Airport",
    "PHL": "Philadelphia International Airport",
    "PHX": "Phoenix Sky Harbor International Airport",
    "PIA": "General Wayne A. Downing Peoria International Airport",
    "PIT": "Pittsburgh International Airport",
    "PPE": "Mar de Cort\xe9s International Airport",
    "PVR": "Licenciado Gustavo D\xedaz Ordaz International Airport",
    "PWM": "Portland International Jetport Airport",
    "RDU": "Raleigh Durham International Airport",
    "RFD": "Chicago Rockford International Airport",
    "RIC": "Richmond International Airport",
    "RND": "Randolph Air Force Base",
    "RNO": "Reno Tahoe International Airport",
    "ROA": "Roanoke\u2013Blacksburg Regional Airport",
    "ROC": "Greater Rochester International Airport",
    "RST": "Rochester International Airport",
    "RSW": "Southwest Florida International Airport",
    "SAN": "San Diego International Airport",
    "SAT": "San Antonio International Airport",
    "SAV": "Savannah Hilton Head International Airport",
    "SBN": "South Bend Regional Airport",
    "SDF": "Louisville International Standiford Field",
    "SEA": "Seattle Tacoma International Airport",
    "SFB": "Orlando Sanford International Airport",
    "SFO": "San Francisco International Airport",
    "SGF": "Springfield Branson National Airport",
    "SHV": "Shreveport Regional Airport",
    "SJC": "Norman Y. Mineta San Jose International Airport",
    "SJD": "Los Cabos International Airport",
    "SKA": "Fairchild Air Force Base",
    "SLC": "Salt Lake City International Airport",
    "SMF": "Sacramento International Airport",
    "SNA": "John Wayne Airport-Orange County Airport",
    "SPI": "Abraham Lincoln Capital Airport",
    "SPS": "Sheppard Air Force Base-Wichita Falls Municipal Airport",
    "SRQ": "Sarasota Bradenton International Airport",
    "SSC": "Shaw Air Force Base",
    "STL": "Lambert St Louis International Airport",
    "SUS": "Spirit of St Louis Airport",
    "SUU": "Travis Air Force Base",
    "SUX": "Sioux Gateway Col. Bud Day Field",
    "SYR": "Syracuse Hancock International Airport",
    "SZL": "Whiteman Air Force Base",
    "TCM": "McChord Air Force Base",
    "TIJ": "General Abelardo L. Rodr\xedguez International Airport",
    "TIK": "Tinker Air Force Base",
    "TLH": "Tallahassee Regional Airport",
    "TOL": "Toledo Express Airport",
    "TPA": "Tampa International Airport",
    "TRI": "Tri Cities Regional Tn Va Airport",
    "TUL": "Tulsa International Airport",
    "TUS": "Tucson International Airport",
    "TYS": "McGhee Tyson Airport",
    "VBG": "Vandenberg Air Force Base",
    "VPS": "Destin-Ft Walton Beach Airport",
    "WRB": "Robins Air Force Base",
    "YEG": "Edmonton International Airport",
    "YHZ": "Halifax / Stanfield International Airport",
    "YOW": "Ottawa Macdonald-Cartier International Airport",
    "YUL": "Montreal / Pierre Elliott Trudeau International Airport",
    "YVR": "Vancouver International Airport",
    "YWG": "Winnipeg / James Armstrong Richardson International Airport",
    "YYC": "Calgary International Airport",
    "YYJ": "Victoria International Airport",
    "YYT": "St. John's International Airport",
    "YYZ": "Lester B. Pearson International Airport",
}
