# Default entrypoint: run Django
web: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 mysite.wsgi:application

# Apply database migrations
migrate: python manage.py migrate && python manage.py collectstatic --verbosity 2 --no-input
