runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /update_schema
  script: update_schema_handler.app  # path to webapp2 application definition.
  login: admin
  secure: always

- url: /add_entities
  script: add_entities_handler.app  # path to webapp2 application definition.
  login: admin
  secure: always

# [START libraries]
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
# [END libraries]
