#  Copyright 2022 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# flake8: noqa


# This file is automatically generated. Please do not modify it directly.
# Find the relevant recipe file in the samples/recipes or samples/ingredients
# directory and apply your changes there.


# [START compute_disk_delete]
import sys
from typing import NoReturn

from google.cloud import compute_v1


def delete_disk(project_id: str, zone: str, disk_name: str) -> NoReturn:
    """
    Deletes a disk from a project.

    Args:
        project_id: project ID or project number of the Cloud project you want to use.
        zone: name of the zone in which is the disk you want to delete.
        disk_name: name of the disk you want to delete.
    """
    disk_client = compute_v1.DisksClient()
    operation = disk_client.delete_unary(project=project_id, zone=zone, disk=disk_name)
    operation_client = compute_v1.ZoneOperationsClient()
    operation = operation_client.wait(
        project=project_id, zone=zone, operation=operation.name
    )

    if operation.error:
        print("Error during disk delete operation:", operation.error, file=sys.stderr)
        raise RuntimeError(operation.error)
    if operation.warnings:
        print("Warnings during disk delete operation:\n", file=sys.stderr)
        for warning in operation.warnings:
            print(f" - {warning.code}: {warning.message}", file=sys.stderr)
    return


# [END compute_disk_delete]
