#  Copyright 2024 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# flake8: noqa


# This file is automatically generated. Please do not modify it directly.
# Find the relevant recipe file in the samples/recipes or samples/ingredients
# directory and apply your changes there.


# [START compute_instance_attach_regional_disk_force]

from __future__ import annotations

import sys
from typing import Any

from google.api_core.extended_operation import ExtendedOperation
from google.cloud import compute_v1


def wait_for_extended_operation(
    operation: ExtendedOperation, verbose_name: str = "operation", timeout: int = 300
) -> Any:
    """
    Waits for the extended (long-running) operation to complete.

    If the operation is successful, it will return its result.
    If the operation ends with an error, an exception will be raised.
    If there were any warnings during the execution of the operation
    they will be printed to sys.stderr.

    Args:
        operation: a long-running operation you want to wait on.
        verbose_name: (optional) a more verbose name of the operation,
            used only during error and warning reporting.
        timeout: how long (in seconds) to wait for operation to finish.
            If None, wait indefinitely.

    Returns:
        Whatever the operation.result() returns.

    Raises:
        This method will raise the exception received from `operation.exception()`
        or RuntimeError if there is no exception set, but there is an `error_code`
        set for the `operation`.

        In case of an operation taking longer than `timeout` seconds to complete,
        a `concurrent.futures.TimeoutError` will be raised.
    """
    result = operation.result(timeout=timeout)

    if operation.error_code:
        print(
            f"Error during {verbose_name}: [Code: {operation.error_code}]: {operation.error_message}",
            file=sys.stderr,
            flush=True,
        )
        print(f"Operation ID: {operation.name}", file=sys.stderr, flush=True)
        raise operation.exception() or RuntimeError(operation.error_message)

    if operation.warnings:
        print(f"Warnings during {verbose_name}:\n", file=sys.stderr, flush=True)
        for warning in operation.warnings:
            print(f" - {warning.code}: {warning.message}", file=sys.stderr, flush=True)

    return result


def attach_disk_force(
    project_id: str, vm_name: str, vm_zone: str, disk_name: str, disk_region: str
) -> None:
    """
    Force-attaches a regional disk to a compute instance, even if it is
    still attached to another instance. Useful when the original instance
    cannot be reached or disconnected.
    Args:
        project_id (str): The ID of the Google Cloud project.
        vm_name (str): The name of the compute instance you want to attach a disk to.
        vm_zone (str): The zone where the compute instance is located.
        disk_name (str): The name of the disk to be attached.
        disk_region (str): The region where the disk is located.
    Returns:
        None
    """
    client = compute_v1.InstancesClient()
    disk = compute_v1.AttachedDisk(
        source=f"projects/{project_id}/regions/{disk_region}/disks/{disk_name}"
    )

    request = compute_v1.AttachDiskInstanceRequest(
        attached_disk_resource=disk,
        force_attach=True,
        instance=vm_name,
        project=project_id,
        zone=vm_zone,
    )
    operation = client.attach_disk(request=request)
    wait_for_extended_operation(operation, "force disk attachment")


# [END compute_instance_attach_regional_disk_force]
