# Copyright 2015 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

# This creates a Postgres Replication Controller with 1  Pod.
# It mounts a GCE persistent disk and database secrets.

metadata:
  name: postgres
apiVersion: v1
kind: ReplicationController
spec:
  replicas: 1
  selector:
    name: postgres
  template:
    metadata:
      labels:
         name: postgres
    spec:
      containers:
      - name: postgres
        image: gcr.io/$GCLOUD_PROJECT/postgres-pw
        # disable this in production
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /usr/local/var/postgres
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      # PostgreSQL Data
      # Replace this with the persistent disk of your choice
      # TODO: replace with Persistent Volume
      volumes:
      - name: postgresdata
        gcePersistentDisk:
          # your disk name here
          pdName: pg-data
          fsType: ext4
      - name: secrets
        secret:
          secretName: db-passwords
---
metadata:
 name: "postgres"
kind: "Service"
apiVersion: "v1"
spec:
  ports:
  - name: "postgres"
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    name: postgres
