# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter_v1alpha3/proto/services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.cloud.securitycenter_v1alpha3.proto import messages_pb2 as google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/securitycenter_v1alpha3/proto/services.proto',
  package='google.cloud.securitycenter.v1alpha3',
  syntax='proto3',
  serialized_pb=_b('\n9google/cloud/securitycenter_v1alpha3/proto/services.proto\x12$google.cloud.securitycenter.v1alpha3\x1a\x1cgoogle/api/annotations.proto\x1a\x39google/cloud/securitycenter_v1alpha3/proto/messages.proto\x1a\x1bgoogle/protobuf/empty.proto2\xdb\x07\n\x0eSecurityCenter\x12\xc4\x01\n\x0cSearchAssets\x12\x39.google.cloud.securitycenter.v1alpha3.SearchAssetsRequest\x1a:.google.cloud.securitycenter.v1alpha3.SearchAssetsResponse\"=\x82\xd3\xe4\x93\x02\x37\"2/v1alpha3/{org_name=organizations/*}/assets:search:\x01*\x12\xb8\x01\n\x0bModifyAsset\x12\x38.google.cloud.securitycenter.v1alpha3.ModifyAssetRequest\x1a+.google.cloud.securitycenter.v1alpha3.Asset\"B\x82\xd3\xe4\x93\x02<\"7/v1alpha3/{org_name=organizations/*}/assets/{id}:modify:\x01*\x12\xcc\x01\n\x0eSearchFindings\x12;.google.cloud.securitycenter.v1alpha3.SearchFindingsRequest\x1a<.google.cloud.securitycenter.v1alpha3.SearchFindingsResponse\"?\x82\xd3\xe4\x93\x02\x39\"4/v1alpha3/{org_name=organizations/*}/findings:search:\x01*\x12\xb4\x01\n\rCreateFinding\x12:.google.cloud.securitycenter.v1alpha3.CreateFindingRequest\x1a-.google.cloud.securitycenter.v1alpha3.Finding\"8\x82\xd3\xe4\x93\x02\x32\"-/v1alpha3/{org_name=organizations/*}/findings:\x01*\x12\xc0\x01\n\rModifyFinding\x12:.google.cloud.securitycenter.v1alpha3.ModifyFindingRequest\x1a-.google.cloud.securitycenter.v1alpha3.Finding\"D\x82\xd3\xe4\x93\x02>\"9/v1alpha3/{org_name=organizations/*}/findings/{id}:modify:\x01*B~\n(com.google.cloud.securitycenter.v1alpha3ZRgoogle.golang.org/genproto/googleapis/cloud/securitycenter/v1alpha3;securitycenterb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n(com.google.cloud.securitycenter.v1alpha3ZRgoogle.golang.org/genproto/googleapis/cloud/securitycenter/v1alpha3;securitycenter'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SecurityCenterStub(object):
    """Service for Cloud Security Command Center.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SearchAssets = channel.unary_unary(
          '/google.cloud.securitycenter.v1alpha3.SecurityCenter/SearchAssets',
          request_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsRequest.SerializeToString,
          response_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsResponse.FromString,
          )
      self.ModifyAsset = channel.unary_unary(
          '/google.cloud.securitycenter.v1alpha3.SecurityCenter/ModifyAsset',
          request_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyAssetRequest.SerializeToString,
          response_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Asset.FromString,
          )
      self.SearchFindings = channel.unary_unary(
          '/google.cloud.securitycenter.v1alpha3.SecurityCenter/SearchFindings',
          request_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsRequest.SerializeToString,
          response_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsResponse.FromString,
          )
      self.CreateFinding = channel.unary_unary(
          '/google.cloud.securitycenter.v1alpha3.SecurityCenter/CreateFinding',
          request_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.CreateFindingRequest.SerializeToString,
          response_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.FromString,
          )
      self.ModifyFinding = channel.unary_unary(
          '/google.cloud.securitycenter.v1alpha3.SecurityCenter/ModifyFinding',
          request_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyFindingRequest.SerializeToString,
          response_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.FromString,
          )


  class SecurityCenterServicer(object):
    """Service for Cloud Security Command Center.
    """

    def SearchAssets(self, request, context):
      """Search assets within an organization.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ModifyAsset(self, request, context):
      """Modifies the marks on the specified asset.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SearchFindings(self, request, context):
      """Search findings within an organization.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def CreateFinding(self, request, context):
      """Creates a finding, creating the same finding with a later event_time will
      update the existing one. CSCC provides the capability for users to search
      findings based on timestamps.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ModifyFinding(self, request, context):
      """Provides a way for users to update mutable parts of a given finding.
      Modifies marks on a finding.
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SecurityCenterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SearchAssets': grpc.unary_unary_rpc_method_handler(
            servicer.SearchAssets,
            request_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsRequest.FromString,
            response_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsResponse.SerializeToString,
        ),
        'ModifyAsset': grpc.unary_unary_rpc_method_handler(
            servicer.ModifyAsset,
            request_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyAssetRequest.FromString,
            response_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Asset.SerializeToString,
        ),
        'SearchFindings': grpc.unary_unary_rpc_method_handler(
            servicer.SearchFindings,
            request_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsRequest.FromString,
            response_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsResponse.SerializeToString,
        ),
        'CreateFinding': grpc.unary_unary_rpc_method_handler(
            servicer.CreateFinding,
            request_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.CreateFindingRequest.FromString,
            response_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.SerializeToString,
        ),
        'ModifyFinding': grpc.unary_unary_rpc_method_handler(
            servicer.ModifyFinding,
            request_deserializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyFindingRequest.FromString,
            response_serializer=google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'google.cloud.securitycenter.v1alpha3.SecurityCenter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSecurityCenterServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Service for Cloud Security Command Center.
    """
    def SearchAssets(self, request, context):
      """Search assets within an organization.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ModifyAsset(self, request, context):
      """Modifies the marks on the specified asset.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SearchFindings(self, request, context):
      """Search findings within an organization.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def CreateFinding(self, request, context):
      """Creates a finding, creating the same finding with a later event_time will
      update the existing one. CSCC provides the capability for users to search
      findings based on timestamps.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ModifyFinding(self, request, context):
      """Provides a way for users to update mutable parts of a given finding.
      Modifies marks on a finding.
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSecurityCenterStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """Service for Cloud Security Command Center.
    """
    def SearchAssets(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Search assets within an organization.
      """
      raise NotImplementedError()
    SearchAssets.future = None
    def ModifyAsset(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Modifies the marks on the specified asset.
      """
      raise NotImplementedError()
    ModifyAsset.future = None
    def SearchFindings(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Search findings within an organization.
      """
      raise NotImplementedError()
    SearchFindings.future = None
    def CreateFinding(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Creates a finding, creating the same finding with a later event_time will
      update the existing one. CSCC provides the capability for users to search
      findings based on timestamps.
      """
      raise NotImplementedError()
    CreateFinding.future = None
    def ModifyFinding(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Provides a way for users to update mutable parts of a given finding.
      Modifies marks on a finding.
      """
      raise NotImplementedError()
    ModifyFinding.future = None


  def beta_create_SecurityCenter_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'CreateFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.CreateFindingRequest.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyAsset'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyAssetRequest.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyFindingRequest.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchAssets'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsRequest.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchFindings'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsRequest.FromString,
    }
    response_serializers = {
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'CreateFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyAsset'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Asset.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchAssets'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsResponse.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchFindings'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsResponse.SerializeToString,
    }
    method_implementations = {
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'CreateFinding'): face_utilities.unary_unary_inline(servicer.CreateFinding),
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyAsset'): face_utilities.unary_unary_inline(servicer.ModifyAsset),
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyFinding'): face_utilities.unary_unary_inline(servicer.ModifyFinding),
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchAssets'): face_utilities.unary_unary_inline(servicer.SearchAssets),
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchFindings'): face_utilities.unary_unary_inline(servicer.SearchFindings),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_SecurityCenter_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'CreateFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.CreateFindingRequest.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyAsset'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyAssetRequest.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.ModifyFindingRequest.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchAssets'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsRequest.SerializeToString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchFindings'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsRequest.SerializeToString,
    }
    response_deserializers = {
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'CreateFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyAsset'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Asset.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'ModifyFinding'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.Finding.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchAssets'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchAssetsResponse.FromString,
      ('google.cloud.securitycenter.v1alpha3.SecurityCenter', 'SearchFindings'): google_dot_cloud_dot_securitycenter__v1alpha3_dot_proto_dot_messages__pb2.SearchFindingsResponse.FromString,
    }
    cardinalities = {
      'CreateFinding': cardinality.Cardinality.UNARY_UNARY,
      'ModifyAsset': cardinality.Cardinality.UNARY_UNARY,
      'ModifyFinding': cardinality.Cardinality.UNARY_UNARY,
      'SearchAssets': cardinality.Cardinality.UNARY_UNARY,
      'SearchFindings': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'google.cloud.securitycenter.v1alpha3.SecurityCenter', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
